# Generated by Django 3.0.7 on 2020-08-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_auto_20200801_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='written_recipe',
            field=models.TextField(null=True),
        ),
    ]
