# Generated by Django 3.0.7 on 2020-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_recipe_written_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
