# Generated by Django 3.0.7 on 2020-08-09 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_auto_20200809_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='written_recipe',
        ),
    ]
