# Generated by Django 3.0.7 on 2020-08-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_auto_20200809_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='img_link',
        ),
    ]
